import 'package:flutter/material.dart';
import '../widgets/main_drawer.dart';
import 'scirun_main_screen.dart';

class ContactsScreen extends StatelessWidget {
  static String routeName = '/contacts';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Contacts'),
      ),
      drawer: MainDrawer(),
      body: Center(
        child: Container(
          padding: EdgeInsets.all(25),
          child: ListView(
            children: <Widget>[
              Text('Module Heads:'),
              Text('Khan Moeen Danish: 03052888000'),
              Text(''),
              Text('TECHNICAL'),
              Text(''),
              Text('Speed Programming'),
              Text('TextACM: Taimur Khan Masud +92 312 9859922'),
              Text('NSS: Fatima Shafqat +92 322 4342762'),
              Text(''),
              Text('Speed Wiring'),
              Text('IEEE: Momin Hashmi +92 331 1332338'),
              Text('NSS: Mian M. Ishaq Khattana +92 300 5386888'),
              Text(''),
              Text('Bamboo Bridge'),
              Text('ASCE: Usama Zulfiqar +92 301 7280924'),
              Text('NSS: Ahmad Hammad Haider +92 334 4237873'),
              Text(''),
              Text('Gear Grind'),
              Text('NSME: Zain ul Abidin +92 332 4529118'),
              Text('NSS: M. Ahmad +92 336 0008278'),
              Text(''),
              Text('Line Following Robot'),
              Text('NRC: Hamis Haider +92 323 4645452'),
              Text('NSS: SM Haisam Tirmizi +92 310 1552299'),
              Text(''),
              Text('Cading'),
              Text('IMechE: Abdullah Zafar +92 317 4927040'),
              Text('NSS: Raees Ahmad Jaleel +92 300 5203510'),
              Text(''),
              Text('Chemathon'),
              Text('AIChe: Abdullah Zahid +92 335 0610068'),
              Text('NSS: M. Huzaifa Zahid +92 332 8640898'),
              Text(''),
              Text('NON-TECHNICAL'),
              Text(''),
              Text('Escape Room'),
              Text('Saad Anwar Sheikh'),
              Text('0304 4138558'),
              Text('Abdul Manan Haider'),
              Text('0337 1475817'),
              Text(''),
              Text('Mathletics'),
              Text('M.Hanzala'),
              Text('0300 8188899'),
              Text('Umar Zeeshan'),
              Text('0320 2073355'),
              Text(''),
              Text('Crimeline'),
              Text('M.Inam ul Haq'),
              Text('0333 5348128'),
              Text('Jahangir Rana'),
              Text('0332 6640252'),
              Text(''),
              Text('Mind Maze'),
              Text('Danyal Zahid'),
              Text('0310 5327249'),
              Text('Muaz bin Moeen'),
              Text('0335 3396957'),
              Text(''),
              Text('Sci Run'),
              Text('Shah Saud'),
              Text('0335 0749505'),
              Text('S.Haseeb Asim Zaidi'),
              Text('0303 4180352'),
              Text(''),
              Text('Medical Mayhem'),
              Text('S.Taueed Ahmed Ali'),
              Text('0336 6213061'),
              Text('Maryam Akhtar Muqaddas'),
              Text('0330 3578722'),
              Text(''),
              Text('Rube Goldberg Machine'),
              Text('Abdul Rehman Arif'),
              Text('0313 6111008'),
              Text(''),
              Text('Make & Test'),
              Text('M.Badar Khalid'),
              Text('0310 9064467'),
              Text('Ayesha Mufaz'),
              Text('0331 5355474'),
            ],
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.arrow_forward),
        onPressed: () {
          Navigator.of(context).pushNamed(ScirunMainScreen.routeName);
        },
      ),
    );
  }
}
